### ISSUE TITLE
Retrieve sorted stdlibs from the json based on the dependency tree

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-release#1030]
**Description:**
Stdlib dependency order is required for cache generation. Currently this has been sorted in Gradle configurations. Ideally this has to be loaded from JSON based on the dependency tree

**Comment by udda1996** [comment]
The fix for this issue is added in this PR https://github.com/ballerina-platform/ballerina-distribution/pull/2129/files
