### ISSUE TITLE
Enable stage central push for ballerinax

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-release#1192]
**Description:**
Currently following extensions are not packed inside the distribution. Hence for daily builds we need to publish these to stage central as we have done for connectors

- [ ] nats
- [ ] stan
- [ ] jaeger
- [ ] prometheus
- [ ] choreo
- [ ] kafka
- [ ] rabbitmq
- [ ] java.jdbc
- [ ] mssql
- [ ] mysql
- [ ] oracledb
- [ ] postgresql

**Comment by udda1996** [comment]
- https://github.com/ballerina-platform/module-ballerinax-nats/pull/292
- https://github.com/ballerina-platform/module-ballerinax-stan/pull/232
- https://github.com/ballerina-platform/module-ballerinax-jaeger/pull/102
- https://github.com/ballerina-platform/module-ballerinax-prometheus/pull/103
- https://github.com/ballerina-platform/module-ballerinax-choreo/pull/124
- https://github.com/ballerina-platform/module-ballerinax-kafka/pull/306
- https://github.com/ballerina-platform/module-ballerinax-rabbitmq/pull/268
- https://github.com/ballerina-platform/module-ballerinax-java.jdbc/pull/284
- https://github.com/ballerina-platform/module-ballerinax-mssql/pull/86
- https://github.com/ballerina-platform/module-ballerinax-mysql/pull/279
- https://github.com/ballerina-platform/module-ballerinax-oracledb/pull/66
- https://github.com/ballerina-platform/module-ballerinax-postgresql/pull/91
