### ISSUE TITLE
Create workflow to publish central stage and dev servers

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-release#1614]
**Description:**
We need to sync central live modules in dev and stage servers. Currently live server is updated by the release workflows of each modules. 

To push same stdlibs in the stage and dev nodes we need to create a separate workflow. This can be triggered after a release(ballerina-distribution). iterate module list then clone each release tag/branch and build and push

**Comment by niveathika** [comment]
Closing as this is implemented
