### ISSUE TITLE
Create workflow to delete all stdlibs published to stage environment 

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-release#1966]
**Description:**
The stdlibs are published to stage environment in RC vote for module owners to test. This needs to be deleted when GA is released  or RC vote fails.

**Comment by SumayyaZiyad** [comment]
- [ ] Setup workflow configuration - triggered manually
- [ ] Retrieve name and version details of stdlibs pushed to staging central
- [ ] Execute stdlib delete
- [ ] Testing
