### ISSUE TITLE
2201.8.x build pipeline failure due to persists and nballerina

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-release#2583]
2201.8.x build pipeline failure due to persists and nballerina

**Comment by SasinduDilshara** [comment]
The reason for the nballerina failure is
https://github.com/ballerina-platform/ballerina-lang/pull/41519

**Comment by SasinduDilshara** [comment]
The reason for the persists failure is [changes](https://github.com/ballerina-platform/ballerina-lang/pull/41549) in the `formatter` affected to the `persist-tool` tests.
`persists-tool` needs to be update according to the formatter changes.
@sahanHe currently working on it.

**Comment by sahanHe** [comment]
This issue in persist-tools was caused by the following update[1] in ballerina formatter as it change the formatting of functions. Currently working on the fix.


[1] - https://github.com/ballerina-platform/ballerina-lang/pull/41549

**Comment by SasinduDilshara** [comment]
Decided to revert the changes of the formatter to fix the persistant module related issue.
https://github.com/ballerina-platform/ballerina-lang/pull/41708

**Comment by SasinduDilshara** [comment]
> Decided to revert the changes of the formatter to fix the persistant module related issue. [ballerina-platform/ballerina-lang#41708](https://github.com/ballerina-platform/ballerina-lang/pull/41708)

Changed the decision to update the persists module

**Comment by SasinduDilshara** [comment]
Pesists changes are reverted by https://github.com/ballerina-platform/persist-tools/pull/321

**Comment by SasinduDilshara** [comment]
fixed now
