### ISSUE TITLE
[2201.4.3] Full build pipline fails

### ISSUE THREAD

**Issue by sahanHe** [ballerina-platform/ballerina-release#2605]
**Description:**
Full build pipeline fails when building ballerina lang - [https://github.com/ballerina-platform/ballerina-release/actions/runs/7071905430/job/19250129116](https://github.com/ballerina-platform/ballerina-release/actions/runs/7071905430/job/19250129116)

**Comment by dulajdilshan** [comment]
Closing as now the full build pipeline passes. Created https://github.com/ballerina-platform/ballerina-lang/issues/41702 to track the issue faced.
