### ISSUE TITLE
[Release Progress] 2201.8.5 - Ballerina Update 8 Patch 5

### ISSUE THREAD

**Issue by tharindu-nw** [ballerina-platform/ballerina-release#2623]
**Description:**
This issue tracks the progress of Ballerina 2201.8.5 release

**Comment by dilanSachi** [comment]
Decided to disable the test cases temporarily as these are not reproducible locally and also in module build - https://github.com/ballerina-platform/ballerina-dev-tools/pull/331

**Comment by dilanSachi** [comment]
Closing this as this is completed now. Details about the faced security vulnerability can be found here - https://github.com/wso2-enterprise/internal-support-ballerina/issues/600
