### ISSUE TITLE
[Update 9] Release progress

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-release#2632]
**Description:**
$subject

**Comment by SasinduDilshara** [comment]
Triggered the RC1 build and it got failed due to https://github.com/ballerina-platform/ballerina-release/issues/2652

**Comment by SasinduDilshara** [comment]
Triggered the Rc1 release and got failed due to https://github.com/ballerina-platform/ballerina-release/issues/2653
