### ISSUE TITLE
[Release Progress] 2201.9.2 - Ballerina Update 9 Patch 2

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-release#2707]
**Description:**
This issue tracks the progress of Ballerina 2201.9.2 release

**Comment by TharmiganK** [comment]
OpenAPI tool issues: 
- https://github.com/ballerina-platform/ballerina-library/issues/6655

**Comment by LakshanWeerasinghe** [comment]
Closing since `2201.9.2` was released.
