### ISSUE TITLE
Send chat notifications for Observability Extension Repos to Observability Team Chat

### ISSUE THREAD

**Issue by nadundesilva** [ballerina-platform/ballerina-release#561]
**Description:**
Currently all chat notifications are send to Ballerina main chat. However, since Observability Extensions are maintained by a different team, we need to send these notifications to the Observability Team Chat.

Repos:
- https://github.com/ballerina-platform/module-ballerinax-prometheus
- https://github.com/ballerina-platform/module-ballerinax-jaeger
- https://github.com/ballerina-platform/module-ballerinax-choreo

**Comment by keizer619** [comment]
Now we notify general chat and include following daily jobs for same 

https://github.com/ballerina-platform/module-ballerinax-prometheus/pull/101
https://github.com/ballerina-platform/module-ballerinax-jaeger/pull/100
https://github.com/ballerina-platform/module-ballerinax-choreo/pull/122

**Comment by niveathika** [comment]
Closing this as general notify chat is used for all notifications
